name: Sync Labels

on:
  workflow_dispatch:
  schedule:
    - cron: "15 3 * * 1" # sync setiap Senin jam 03:15 GMT
  push:
    branches:
      - main
    paths:
      - ".github/labels.yml"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync labels from org config
        uses: EndBug/label-sync@v2
        with:
          config-file: https://raw.githubusercontent.com/native-productions/.github/main/.github/labels.yml
          delete-other-labels: false # tetap aman tidak hapus label custom repo